### ISSUE TITLE
registerCallbacks

### ISSUE THREAD

**Issue by pablomayobre** [rm-code/screenmanager#1]
This is a feature included in Hump states, which basically registers ScreenManager to all the callbacks LÖVE provides, of course if you redefine a callback later on you will probably override ScreenManager, but is nice to have when ScreenManager is what handles the structure of the game.

The code is really simple:
```lua
--Register event handlers callbacks
local all_callbacks = { 'draw', 'update' }
for k in pairs(love.handlers) do
  all_callbacks[#all_callbacks+1] = k
end

function ScreenManager.registerCallbacks( callbacks )
  local registry = {}
  callbacks = callbacks or all_callbacks
  for _, f in ipairs( callbacks ) do
    registry[f] = love[f] or NULL
    love[f] = function( ... )
      registry[f]( ... )
      return ScreenManager[f]( ... )
    end
  end
end
```

This code is taken from [hump.gamestate](https://github.com/vrld/hump/blob/master/gamestate.lua#L78L93) and credits should go to @vrld

**Comment by rm-code** [comment]
I don't really understand what this would do ^^ Would this mean you could call ScreenManager.draw() directly instead of hooking it into `main.lua` and the `love.draw` callback?

**Comment by pablomayobre** [comment]
This means you can have a `main.lua` file like this one:
```lua
love.load = function ()
  local ScreenManager = require "ScreenManager"

  local screens = {
    splash  = require "src.splash",
    menu    = require "src.menu"
  }

  ScreenManager.init(screens, "splash", "menu")

  --Register to all love events
  ScreenManager.registerCallbacks()
end
```

And `ScreenManager` now has control of all the callbacks so my states can define `update`, `mousepressed`... functions even though I haven't called `ScreenManager.update(dt)`, `ScreenManager.mousepressed(x, y, b, istouch)`... by hand.

**Comment by rm-code** [comment]
Ok that's what I meant. Sounds convenient.

I'll try to implement it before the jam, but I can't promise anything because I'm pretty tied up because of work and working on my game :)

**Comment by pablomayobre** [comment]
You can check the code I wrote [here](https://github.com/rm-code/screenmanager/compare/master...Positive07:registerCallbacks). And if you want then I can create a PR

**Comment by pablomayobre** [comment]
Should I make a PR so we start a review or would you prefere to wait?

**Comment by rm-code** [comment]
Feel free to open a PR for this one. I'd prefer to have the callbacks as a constant list at the top of the lib instead of using
```
local all_callbacks = { 'draw', 'update' }
for k in pairs(love.handlers) do
  all_callbacks[#all_callbacks+1] = k
end
```

**Comment by pablomayobre** [comment]
They were a lot and I was lazy hahaha I guess I'll grab the list from `Screen.lua`

It's a long list though, are you sure you want this at the top:
```lua
local allcallbacks = {
    'directorydropped',
    'draw',
    'filedropped',
    'focus',
    'keypressed',
    'keyreleased',
    'lowmemory',
    'mousefocus',
    'mousemoved',
    'mousepressed',
    'mousereleased',
    'quit',
    'resize',
    'textedited',
    'textinput',
    'threaderror',
    'touchmoved',
    'touchpressed',
    'touchreleased',
    'update',
    'visible',
    'wheelmoved',
    'gamepadaxis',
    'gamepadpressed',
    'gamepadreleased',
    'joystickadded',
    'joystickaxis',
    'joystickhat',
    'joystickpressed',
    'joystickreleased',
    'joystickremoved',
}
```
