### ISSUE TITLE
Renaming ScreenManager.lua to init.lua

### ISSUE THREAD

**Issue by pablomayobre** [rm-code/screenmanager#14]
Have you considered this possibility?

In my [lovejam-training](https://github.com/Positive07/lovejam-training) repo (which I should probably rename to love-template haha) I renamed `ScreenManager.lua` to `init.lua` and placed it inside a folder called `State` but could have called it `ScreenManager`

The idea behind this is that you could use the repository as a submodule, or directly clone the repository into your project and use it without having to grab two files and placing them with many other libraries. They can stay in their own folder together.

**Comment by rm-code** [comment]
IIRC using `init.lua` changes the way Lua requires files?

> The idea behind this is that you could use the repository as a submodule, or directly clone the repository into your project and use it without having to grab two files and placing them with many other libraries. They can stay in their own folder together.

Can't you do that right now?

```
cd lib
git clone git@github.com:rm-code/screenmanager.git

-> require( "lib/ScreenManager/ScreenManager" )

**Comment by pablomayobre** [comment]
What I'm proposing is to have this:
```
cd lib
git clone git@github.com:rm-code/screenmanager.git

-> require "lib.ScreenManager" --This requires init.lua
-> require "lib.ScreenManager.Screen" --This requires Screen.lua

--Screen.lua and init.lua are both inside the lib/ScreenManager folder
```
Which I consider is more ordered, and shorter. Most libraries work this way (SUIT and HUMP are examples that come to mind)

**Comment by rm-code** [comment]
I prefer the explicit requiring of ScreenManager since that's how I create all my libraries, especially if we get rid of `Screen.lua` so I'm closing this.

You could place `ScreenManager.lua` in lib and it would just be `require "lib.ScreenManager"` as well.
