### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by rm-code** [rm-code/screenmanager#16]
I'm currently testing if the screen manager is leaking memory. Looks like switching from one screen to the other doesn't free the memory of the previous screens.

Potentially caused by other stuff in my game though :P

CC @Positive07

**Comment by rm-code** [comment]
Using the example project, opening the overlay and switching to the main menu seems to reproduce the leak.

I upped the amount of created objects to 2000 to show the increase.

Starting with ~800kb:
![screenshot 2017-03-14 09 38 48](https://cloud.githubusercontent.com/assets/11627131/23892235/16ad4476-089a-11e7-909c-1c2dae2a44e9.png)

Calling `collectgarbage( 'collect' )` after a few switches gives us this:
![screenshot 2017-03-14 09 39 01](https://cloud.githubusercontent.com/assets/11627131/23892280/321a07e4-089a-11e7-84cb-a57736cf9178.png)

**Comment by rm-code** [comment]
With `ScreenManager.pop()` I'm able to get it back down to ~800 kb. Strangely enough with `ScreenManager.switch( foo )` it looks like it always goes back down to ~2000kb.

So I'm not sure if it really is a leak.

**Comment by rm-code** [comment]
I changed the `clear` function to internally call ScreenManager.pop and as far as I can tell I now can reduce the memory footprint to ~800kb.
```
local function clear()
    for i = 1, #stack do
        ScreenManager.pop();
    end
end
```

I am confused 🤔

**Comment by pablomayobre** [comment]
Every time you `push` a screen `.new()` is called and a new table with the screen is created, this in turns generates a new table every time you push, which can only be removed from the `stack` table by either `pop` or `switch`

You could make sure that your states are stateful (self is declared outside of the `new` function and `new` always returns the same table)
```lua
local ScreenManager = require( 'ScreenManager' )
local Screen = require( 'Screen' )

local self = Screen.new() -- Note how we inherit from the Screen class.

local x, y, w, h, str, font

function self:init( nstr )
    x, y, w, h = 0, 0, love.graphics.getDimensions()
    str, font = nstr, love.graphics.newFont( 20 )
    love.graphics.setFont( font )
end

function self:draw()
    love.graphics.setColor( 0, 0, 0, 100 )
    love.graphics.rectangle( 'fill', x, y, w, h )
    love.graphics.setColor( 255, 255, 255, 255 )
    love.graphics.print( str, w * 0.5 - font:getWidth( str ) * 0.5, h * 0.5 )
end

function self:keypressed( key )
    if key == 'escape' then
        -- Removes the topmost screen, so in this case the overlay itself.
        ScreenManager.pop()
    elseif key == 'n' then
       -- Closes all screens (close() function will be called) and creates a new screen.
        ScreenManager.switch( 'main' )
    end
end

local Overlay = {}

function Overlay.new()
    return self
end

return Overlay
```

Or alternatively you could prevent pushing the same state twice (#6) but I think that this "prevention" should be outside of ScreenManager.

**Comment by pablomayobre** [comment]
This solution shouldn't work
```lua
local function clear()
    for i = 1, #stack do
        ScreenManager.pop();
    end
end
```
Since `ScreenManager.pop()` just pushes a change to the `changes` table so you are actually delaying the deletion of the state and that can lead to undefined behaviour (deleting the state you are trying to push)

Even if you called the local `pop()` function it should be the same thing as `clear()`

How about something like:
```lua
local function clear()
    while ScreenManager.peek() do
        local tmp = ScreenManager.peek()
        tmp:close()
        stack[#stack] = nil
    end
end
```

**Comment by rm-code** [comment]
Regardless of how many screens we create, the memory should be freed once the table is removed from the stack, right?

The changes table is cleared each time the actions are performed.

> Even if you called the local pop() function it should be the same thing as clear()

Apologies, I meant the local `pop` ... yeah that's why I'm confused. I don't see why it would make a difference, but for some reason the memory isn't freed when I switch between screens.

**Comment by pablomayobre** [comment]
`pop()` and `clear()` do the very same thing... Maybe out of order like:
```lua
local function clear()
    while ScreenManager.peek() do
        local tmp = ScreenManager.peek()
        stack[#stack] = nil`
        tmp:close()
    end
end
```

**Comment by pablomayobre** [comment]
Could you post the example to better track down the issue?

**Comment by rm-code** [comment]
Just to make sure I'm not going crazy ...
[leak_test.zip](https://github.com/rm-code/screenmanager/files/840738/leak_test.zip)

Pressing p pushes a bunch of new screens. N switches back to main. Space collects memory.
-> ~2000kb

Pressing p to push a bunch of new screens. Escape to close them until you are down to the main screen. Space to collect memory.
-> ~800kb

**Comment by pablomayobre** [comment]
I'm guessing that the creation of the new `MainScreen` state created when you `switch` is causing the additional memory consumption. When you just `pop` you are using the same `MainScreen` you started with

**Comment by rm-code** [comment]
Yup that's what I'm thinking as well, but when we use switch shouldn't the memory for the original main screen be freed too?

**Comment by pablomayobre** [comment]
I simplified the `clear()` function to this:
```lua
local function clear()
    for i=#stack, 1, -1 do
        stack[i]:close()
    end

    stack = {}
end
```
But the problem persists, it looks like references to the old states are saved somewhere else so they can't be freed. This change already makes sure that at least the reference are not in the stack but somewhere else

Also I must note that I'm debugging with this code:
```lua
function ScreenManager.performChanges()
    if #changes == 0 then
        return
    end

    for _, change in ipairs( changes ) do
      if change.action == 'pop' then
          pop()
      elseif change.action == 'switch' then
          print("---")
          collectgarbage("collect")
          print(">", collectgarbage("count"))
          clear()
          collectgarbage("collect")
          print(">", collectgarbage("count"))
          push( change.screen, change.args )
          collectgarbage("collect")
          print(">", collectgarbage("count"))
          print("---")
      elseif change.action == 'push' then
          push( change.screen, change.args )
      end
    end

    changes = {}
end
```
And I get a steady 2000, doesn't matter the number of states I push

I tried pushing only MainScreen's to see if the problem was in Overlay but the issue persists.
I stopped allocating the font to make sure that LÖVE wasn't storing references itself but that wasn't the issue

I have to go now. I will try at night

**Comment by rm-code** [comment]
@Positive07 
I changed my `main.lua` to manually use the love callbacks instead of using the register functionality. It looks like memory is freed correctly now ... could you please test and confirm when you have the time?

```lua
local ScreenManager = require( 'ScreenManager' )

function love.load()
    -- This list specifies all screens our ScreenManager can create and use.
    -- We can use it later by creating a screen via `ScreenManager:push( str )`.
    local screens = {
        ['main']    = require( 'MainScreen' ),
        ['overlay'] = require( 'Overlay' )
    };

    -- Apply the list to the ScreenManager and create the first screen.
    ScreenManager.init( screens, 'main' )
    -- ScreenManager.registerCallbacks()
end

function love.update()
    ScreenManager.update();
end

function love.draw()
    love.graphics.print( collectgarbage( 'count' ), 10, love.graphics.getHeight() - 20 );
    ScreenManager.draw();
end

function love.keypressed( key )
    ScreenManager.keypressed( key )
end
```

**Comment by rm-code** [comment]
Wtf ... I just tested it again and it goes back up to 1400. At this point I'm wondering if it's just something random happening with the qc that isn't actually an issue in ScreenManager.

**Comment by rm-code** [comment]
Ok looks like it has something to do with the `update` callback. Commenting that in and out I can now reliably reproduce the gc issue.

**Comment by rm-code** [comment]
[no_update.zip](https://github.com/rm-code/screenmanager/files/841354/no_update.zip)
[update.zip](https://github.com/rm-code/screenmanager/files/841355/update.zip)

**Comment by tapir** [comment]
For me in both the number goes up and up even when doing nothing. but when I push overlay it alternates between 800-2000 for no update and between 2000-5000 for update.
Are these the numbers that I should see?
Why is the memory consumption always counts up even when doing nothing?

**Comment by rm-code** [comment]
> Why is the memory consumption always counts up even when doing nothing?

@tapir LÖVE leaks a small amount of memory each frame. Check [this PR](https://bitbucket.org/rude/love/pull-requests/81/fix-loveeventpoll-leak/diff) on the LÖVE repository.
Usually this shouldn't be a problem because the garbage collector kicks in to free that memory eventually.

It might be a LÖVE thing, which causes the ScreenManager test to hover at 800kb without the `update` callback and at 2000kb with it enabled.

I don't think it's really a leak within ScreenManager.

**Comment by rm-code** [comment]
Looks like I finally found the actual culprit. It seems like LuaJIT prevents the collection of memory for functions called from the closures.

I wrote a small test that calls the same script from both LÖVE and Lua:

```
> lua test.lua
preCreation	24.9140625	936
preCollection	345416.2890625	296
postCollection	24.4453125	456

> luajit test.lua
preCreation	28.1396484375
preCollection	220133.54199219
postCollection	219625.75683594
```

I opened an issue in the LuaJIT repository to ask for help / a fix. As far as I can tell a workaround for the moment is to not use upvalues (which of course isn't really an option for functions like update).

**Comment by tapir** [comment]
That is some crazy find! Kudos. Is luajit still maintained? I heard the
author was retired?

2017-03-15 21:34 GMT+03:00 Robert Machmer <notifications@github.com>:

**Comment by tapir** [comment]
Can you share your test app?

**Comment by rm-code** [comment]
@tapir I reported the error here https://github.com/LuaJIT/LuaJIT/issues/303 - it contains the script I used for testing.

**Comment by pablomayobre** [comment]
So this was a LuaJIT issue and not a problem with the code. Is there some workaround we can implement in order to work around this? (since it will probably take some time for LuaJIT to fix the issue, and some more time until a stable release is actually released, and LÖVE bumps to it)

**Comment by rm-code** [comment]
https://github.com/LuaJIT/LuaJIT/issues/303#issuecomment-287330289 mentions to use `jit.flush` to clear up any cached references.

An obvious solution would be adding `jit.flush` to the `switch` function, but IMO it would make more sense to document it somewhere instead of enforcing it.
