### ISSUE TITLE
Switching or Pushing a state should be delayed

### ISSUE THREAD

**Issue by pablomayobre** [rm-code/screenmanager#2]
The problem is that when you call `ScreenManager.switch` or `ScreenManager.push` in a callback of a state, the other callbacks are delivered to the state you switched to, so for example if you were in a menu and in the `mousepressed` callback you switch to the game, the `keypressed` and `textinput` callbacks will be from the game state and not actually from the menu which is the state you were actually updating this frame.

This may be good for some use cases but is bad for others. [HUMP handles this by halting the state](https://github.com/vrld/hump/issues/46) which works like this: you are in the menu, in the `mousepressed` callback you switch to the game, the rest of the callbacks will be ignored until the `update` callback is called and the game gets updated, then the next frame you get the callbacks normally. I consider this bad behaviour since there are callbacks you are not handling correctly and it may lead to a black frame.

My alternative would be the following, delay the state switch until after the `draw` callback. In this way you guarantee that the current state will be active until the next frame, and only the last switching/pushing/popping operation will be valid

Different use cases probably demands different behaviours, so I wanted to start the discussion.

I use a [delayed switch in my code](https://github.com/Positive07/lovejam-training/blob/master/lib/state/init.lua), but I also have a public function that allows me to change the states immediately called `performChange` and should be used after a `push`, `pop` or `switch` to get an immediate switch

**Comment by rm-code** [comment]
I already had problems with this myself in an earlier game so I'd like to implement this as well.

As with #1 I'm not sure when I'll get to it though.

**Comment by pablomayobre** [comment]
You can check the code I wrote [here](https://github.com/rm-code/screenmanager/compare/master...Positive07:delay-change). And if you want then I can create a PR

**Comment by rm-code** [comment]
Feel free to open a PR for this one too. I'll try to review and test it this weekend 👍

**Comment by rm-code** [comment]
@Positive07 I wanted to publish the new release just now, but I think there is a problem with our current approach of using the change variable.

What if the user wants to pop() two screens from the current screen? Imagine something like this: You have a game screen, the player opens an inventory screen and in that screen he opens an compare items screen. For the player it would be convenient to just press 'i' to close the inventory screen.

This wouldn't be possible with https://github.com/rm-code/screenmanager/commit/c27ea3d3ccbe68f8c36e07045ecf22d7de386443 if I'm not mistaken. But it's not a hard issue to fix. We could simply use a "queue" for the actions.

I'm thinking about something like this:
```lua
local changes = {};

...
function ScreenManager.switch( screen, ... )
    validateScreen( screen );
    changes[#changes + 1] = { action = 'switch', screen = screen, args = { ... } };
end
...

function ScreenManager.performChange()
    if #changes == 0 then
        return
    end

    for _, change in ipairs( changes ) do
        if change.action == 'pop' then
            pop();
        elseif change.action == 'switch' then
            clear();
            push( change.screen, change.args );
        elseif change.action == 'push' then
            push( change.screen, change.args );
        end
    end

    changes = {};
end
```

Would this make sense? Are you seeing problems with this approach?

**Comment by pablomayobre** [comment]
The problem with that is that if you switch and then pop we have no way to know that we popped the last state and that an error should be raised. You could pop 10 times when there are only 3 states in the stack...

If we did this then we at least need a variable to know how many items are there in the stack, switch turns this number to 1, push increments it, pop decrements it when it's 1 you can't pop anymore.

Other alternative is keeping a separate stack and switching it on draw or something like that, but this requires you to make at least a shallow copy of the stack each time you `performChange`

This probably deserves a new issue
