### ISSUE TITLE
Avoid creating 33 null functions in Screen.new

### ISSUE THREAD

**Issue by pablomayobre** [rm-code/screenmanager#3]
In `Screen.new` you define functions fo each of LÖVE's callbacks and all of this functions are empty, so you could define a single empty function and use it repeatedly for all of the different callbacks.

This is a minor issue, I doubt that it represents a slowdown or a bottleneck but there is no disadvantage in fixing this either.

**Comment by pablomayobre** [comment]
You can check the code I wrote [here](https://github.com/rm-code/screenmanager/compare/master...Positive07:null-function). And if you want then I can create a PR

**Comment by rm-code** [comment]
Looks good to me. If you open a PR for it I'd gladly merge it :)
