### ISSUE TITLE
Prevent pushing of multiple screens of the same type

### ISSUE THREAD

**Issue by rm-code** [rm-code/screenmanager#6]
In [OTR](rmcode.itch.io/on-the-roadside) I had a bug with the ScreenManager because it allows you to push the same screen multiple times.

I think `push`should throw an error if a screen of the same type is already on the stack unless you manually "force" it with a flag such as `allowDuplicate`.

**Comment by pablomayobre** [comment]
We could make it so that `isValidScreen` checks if this screen is on the stack already. 

Does it need to check the whole stack or only the last screen (with `:peek()`)? Does it need to error or could it just ignore the action silently (maybe returning a boolean value)?

**Comment by rm-code** [comment]
I'd say it should throw an error unless the programmer explicitly sets a flag for ignoring duplicate screens. But maybe this is inconvenient to other users. 

Personally I haven't come across situations where I needed to push multiple screens of the same type over each other, but who knows what others might do ^^

**Comment by pablomayobre** [comment]
I have a screen which takes some values when `init` is called, this values are then used to change how the screen looks, I can use this to push the same screen but get "different screens"

I use this to load levels, I have a level-loader and passing the level number in init actually picks the level, so I don't really need to create a Screen for each level, but to be honest I never have two levels running at the same time. But I imagine you could use this for something like framed windows (UI) and they could all be active at the same time... 

I can't think of other use case for repeated states though.

**Comment by pablomayobre** [comment]
We could let the user of the library make that decision by providing a function like:
```lua
function ScreenManager.isInStack( screen )
    validateScreen( screen ); -- Could return false instead of erroring
    local state = screens[screen];

    for _, v in ipairs( stack ) do
        if state == v then
            return true
        end
    end

    return false
end
```
Note that if #2 is fixed with a queue then `isInStack` will not know if the screen you are asking for has already been pushed to the stack and is waiting for `performChange`. So basically `isInStack` and `peek` only hold the real values after `performChange` and until a `pop`/`push`/`switch` is performed

**Comment by rm-code** [comment]
Closing this because after more development for otr I realised that stacking the same screen types (e.g. modals) must be allowed.
