### ISSUE TITLE
ScreenManager:pop() doesn't return the last state

### ISSUE THREAD

**Issue by pablomayobre** [rm-code/screenmanager#7]
The docs and comments say that `ScreenManager:pop()` returns the screen on top of the stack. But this is not true, it doesn't return anything.

This error is gonna be hard to fix once #5 is merged so I think it's probably easier to delete this from the docs and suggest to use `ScreenManager:peek()` which is gonna hold the last state until the next frame anyway.

**Comment by rm-code** [comment]
I can't remember ever using a screen returned by `pop` so chances are it's just a false / leftover comment.

Feel free to fix the documentation :)
